# Generated by Django 5.0.1 on 2024-01-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
