# Generated by Django 5.0.1 on 2024-01-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_registerdb_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterDB',
        ),
    ]
