# Generated by Django 5.0.1 on 2024-01-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterDB',
        ),
    ]
