# Generated by Django 5.0.1 on 2024-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
